### PR TITLE
Fix Guzzle integrations

### LINKED ISSUE #99: Attempted to call an undefined method named "context" of class "OpenCensus\Trace\Tracer".
Hi!

Trying to use the Guzzle middleware always throws an exception : 

```
Symfony\Component\Debug\Exception\UndefinedMethodException:
Attempted to call an undefined method named "context" of class "OpenCensus\Trace\Tracer".

  at vendor/opencensus/opencensus/src/Trace/Integrations/Guzzle/Middleware.php:72
  at OpenCensus\Trace\Integrations\Guzzle\Middleware->OpenCensus\Trace\Integrations\Guzzle\{closure}(object(Request), array('synchronous' => true, 'base_uri' => object(Uri), 'handler' => object(HandlerStack), 'connect_timeout' => 30, 'read_timeout' => 30, 'timeout' => 30, 'allow_redirects' => array('max' => 5, 'protocols' => array('http', 'https'), 'strict' => false, 'referer' => false, 'track_redirects' => false), 'http_errors' => true, 'decode_content' => true, 'verify' => true, 'cookies' => false))
     (vendor/guzzlehttp/guzzle/src/HandlerStack.php:67)
```

It's this line that calls an undefined method : https://github.com/census-instrumentation/opencensus-php/blob/d810becb20ecb67ac072e2f991455172e756262f/src/Trace/Integrations/Guzzle/Middleware.php#L72

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #99

### CODE REVIEW

File: tests/unit/Trace/Integrations/Guzzle/EventSubscriberTest.php [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+use GuzzleHttp\Message\Response;
+use OpenCensus\Trace\Tracer;
+use OpenCensus\Trace\Exporter\ExporterInterface;
+use OpenCensus\Trace\Integrations\Guzzle\EventSubscriber;
+use Prophecy\Argument;
+
+/**
+ * @group trace
+ */
+class EventSubscriberTest extends \PHPUnit_Framework_TestCase
```
Comment (tmatsuo) [inline tests/unit/Trace/Integrations/Guzzle/EventSubscriberTest.php]: phpunit 4.8 is very old. We should move to newer version. You can do it with another PR though.
