### PR TITLE
Fix builds for 32 bit architecture

### LINKED ISSUE #13: Failed test on 32-bit
```
TEST 17/32 [tests/manual_spans_default_options.phpt]
========DIFF========
007+             [spanId:protected] => -1034353423
007-             [spanId:protected] => %d
020+             [spanId:protected] => -851458494
021+             [parentSpanId:protected] => -1034353423
020-             [spanId:protected] => %d
021-             [parentSpanId:protected] => %d
========DONE========
FAIL OpenCensus Trace: Customize the trace span options for a function [tests/manual_spans_default_options.phpt] 

```

### LINKED ISSUE #14: Segfault during test suite
Not always... sometime
Will try to get a bactrace

```
OpenCensus Trace: Basic Class Method As Function Test [tests/basic_class_function.phpt]
OpenCensus Trace: Basic Function Test [tests/basic_function.phpt]
OpenCensus Trace: Basic Method Test [tests/basic_method.phpt]
OpenCensus Trace: Clear Traces [tests/clear_traces.phpt]
OpenCensus Trace: Nested spans [tests/nested_spans.phpt]
OpenCensus Trace: Basic Class Static Method [tests/static_method_test.phpt]
OpenCensus Trace: Trace Context [tests/trace_context.phpt]
```

All with `Termsig=11`

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #13 (unsigned int issue)
Fixes #14 (segfaults with zend_parse_parameters)

### CODE REVIEW

File: ext/opencensus_trace.c [hunk 1]
```diff
@@ -250,7 +252,7 @@ static opencensus_trace_span_t *opencensus_trace_begin(zend_string *function_nam
         php_mt_srand(GENERATE_SEED());
     }
 #endif
-    span->span_id = (php_mt_rand() >> 1);
+    span->span_id = ((uint32_t) php_mt_rand()) >> 1;
```
Comment (tmatsuo) [inline ext/opencensus_trace.c]: So does it pass the test on 32bit? Worth adding some comments?

Comment (chingor13) [inline ext/opencensus_trace.c]: It should pass on 32-bit versions of PHP we now test against PHP 7.0 and 7.1 on a 32-bit debian build.
Also added comment about why this is in here.

Comment (tmatsuo) [inline ext/opencensus_trace.c]: Thanks. It might be a dumb question.

The return value of `php_mt_rand` is `uint32_t` (https://github.com/php/php-src/blob/869fccea24ac829de8ebf9947f6515f03b7d1fe1/ext/standard/mt_rand.c#L163) and I still don't understand why it works.
