### PR TITLE
Extension: Fix timing memory management for callback arguments

### LINKED ISSUE #183: Segfault While Tracing Method
Hi, I’m experiencing segfault with extension in my Symfony project on Ubuntu Xenial and Debain Jessie.
phpinfo() reports that extension version is 0.2.1. Compiled from release v0.5.0.

During debugging I’ve discovered that error disappear if iI avoid tracing of one particular method,
tracing of other methods works fine.

```php
        // public function publish(string $topicName, string $data, array $attributes = [])
        opencensus_trace_method(QueueService::class, 'publish', function ($queue, $topicName) {
            return [
                'name' => 'queue.publish',
                'attributes' => [
                    'topicName' => $topicName
                ]
            ];
        });
```

Also, there is no segfault if I skip callback:

```php
        // public function publish(string $topicName, string $data, array $attributes = [])
        opencensus_trace_method(QueueService::class, 'publish');
```

It’s 100% reproducible on my project, but I’m not sure which minimal test case can reveal this issue.

With gdb attached to PHP-FPM process I was able to get this backtrace:

```
Thread 1 "php-fpm7.1" received signal SIGSEGV, Segmentation fault.
0x000056251320dc12 in _emalloc_56 ()
(gdb) bt
#0  0x000056251320dc12 in _emalloc_56 ()
#1  0x0000562513237e70 in _array_init ()
#2  0x0000562513250ce8 in zend_fetch_debug_backtrace ()
#3  0x00007f105478e020 in opencensus_trace_begin (name=name@entry=0x7f1054ce02a0, span_id=span_id@entry=0x0,
    execute_data=0x7f1054c133f0) at /opencensus-php-0.5.0/ext/opencensus_trace.c:400
#4  0x00007f105478e4d0 in opencensus_trace_execute_ex (execute_data=0x7f1054c133f0)
    at /opencensus-php-0.5.0/ext/opencensus_trace.c:622
#5  0x00005625132d898a in ?? ()
#6  0x000056251327f92b in execute_ex ()
#7  0x00007f105478e561 in opencensus_trace_execute_ex (execute_data=0x7f1054c13340)
    at /opencensus-php-0.5.0/ext/opencensus_trace.c:627
#8  0x00005625132d851e in ?? ()
#9  0x000056251327f92b in execute_ex ()
#10 0x00007f105478e561 in opencensus_trace_execute_ex (execute_data=0x7f1054c13260)
    at /opencensus-php-0.5.0/ext/opencensus_trace.c:627
#11 0x00005625132d851e in ?? ()
#12 0x000056251327f92b in execute_ex ()
#13 0x00007f105478e4dc in opencensus_trace_execute_ex (execute_data=0x7f1054c131b0)
    at /opencensus-php-0.5.0/ext/opencensus_trace.c:623
#14 0x00005625132d851e in ?? ()
#15 0x000056251327f92b in execute_ex ()
#16 0x00007f105478e561 in opencensus_trace_execute_ex (execute_data=0x7f1054c13110)
    at /opencensus-php-0.5.0/ext/opencensus_trace.c:627
#17 0x00005625132d851e in ?? ()
#18 0x000056251327f92b in execute_ex ()
#19 0x00005625132dab10 in zend_execute ()
#20 0x0000562513235de3 in zend_execute_scripts ()
#21 0x00005625131d20e0 in php_execute_script ()
#22 0x00005625130b0079 in main ()
```

I’m not experienced with extensions development or gdb, so please let me know if I can collect some additional info for resolving this issue.

### PR DESCRIPTION
**Pull request by chingor13**
Currently, we are running the watched function callback after executing the traced function which is desired because you can access information about the results of the function (e.g. how many bytes sent/received from a curl request). However, it's possible for the arguments to be deallocated by the memory manager after execution. This can cause undefined behavior (potentially segfaults).

We will instead copy the argument argument zvals before executing the original function, then provide those copies to the callback function.

May fix #183

### CODE REVIEW

File: ext/opencensus_trace.c [hunk 1]
```diff
@@ -657,22 +664,46 @@ void opencensus_trace_execute_internal(INTERNAL_FUNCTION_PARAMETERS)
...
+
+    if (zend_is_callable(trace_handler, 0, &callback_name)) {
+        /* Registered handler is callable - execute the callback */
+        zval callback_result, *args;
+        int num_args;
+        opencensus_copy_args(execute_data, &args, &num_args);
+        resume_execute_internal(INTERNAL_FUNCTION_PARAM_PASSTHRU);
+        if (opencensus_trace_call_user_function_callback(args, num_args, execute_data, span, trace_handler, &callback_result TSRMLS_CC) == SUCCESS) {
+            opencensus_trace_span_apply_span_options(span, &callback_result);
+        }
```
Comment (tmatsuo) [inline ext/opencensus_trace.c]: Is it worth emitting a warning when the user callback fails here?

Comment (chingor13) [reply ext/opencensus_trace.c]: We already raise a warning inside `opencensus_trace_call_user_function_callback` if there's an exception inside of the callback or if the return value is not an array of span attributes. Any other failure is a PHP internal error that should already raise a warning. It's possible that we also raise a warning with a generic message for these cases as well.

Comment (tmatsuo) [reply ext/opencensus_trace.c]: LGTM
